In [135]:
print("Hello World!")

Hello World!


In [136]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np

print(torch.__version__)
print(np.__version__)

2.7.1+cpu
2.3.2


In [137]:
# I dont have a gpu !! just a mac

In [138]:
# Introduction to tensors
# a way to represent data

# How do i know the different types
# Scalar
scalar = torch.tensor(7)
scalar

# A scalar hare dimensions i i can know it using 
print(f"ndim: {scalar.ndim}")
# this has no dimension because is an integer


# Vector
vector = torch.tensor([8, 9])
print(f"ndim of vector: {vector.ndim}")

# Matrix
matrix = torch.tensor([[1, 2], [3, 5]])
print(f"ndim of matrix: {matrix.ndim}")

matrix[0]

matrix.shape

# what is a tensor
tensor = torch.tensor([[[1, 2, 3],
                        [1, 2, 3],
                        [1, 2, 3]
                        ]])
tensor.shape
# This will be 1, 3, 3
tensor2 = torch.tensor([[[1, 2, 3],
                        [1, 2, 3],
                        [1, 2, 3],
                        [1, 2, 3]
                        ]])
tensor2.shape
# This will be 1, 4, 3



ndim: 0
ndim of vector: 1
ndim of matrix: 2


torch.Size([1, 4, 3])

### Random tensors
Why to use random tensor
They are importand because we start from random noise to create a neural net



In [139]:
# Create a random tensor
random_tens = torch.rand(3,4)
random_tens
random_tens.ndim
random_tens.shape

torch.Size([3, 4])

In [140]:
randimg = torch.rand(100, 100, 3) # height, width, colors rgb
randimg.shape; randimg.ndim

# all zeros
zeros = torch.zeros(100, 100, 3)
r0 = randimg * zeros

r0

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [141]:
zeros.dtype

torch.float32

# Ranges

In [142]:

zeros[99][99] = torch.ones(3)
zeros[99][99] 
zeros


tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [1., 1., 1.]]])

In [143]:
# range
torch.arange(0, 11)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [144]:
torch.arange(start=1, end=200, step=12)

tensor([  1,  13,  25,  37,  49,  61,  73,  85,  97, 109, 121, 133, 145, 157,
        169, 181, 193])

In [145]:
# i can use like to crate a similar dim 
ff = torch.arange(0, 100)
zeros_like_ff = torch.zeros_like(ff)
zeros_like_ff

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

In [146]:
# Tensors Data types
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None)

In [147]:
# This is float32 because is the default
float_32_tensor.dtype



torch.float32

In [148]:

# float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16, 
#                                device = None, # is it store in cpu o gpu
#                                # for example you can use "cuda" if you have it
#                                require_grad = False # Track gradients with this tensor
#                                )
# Beware of
# Tensor not right datatype
# Tensor not right shape
# Tensor not on the right device


In [149]:
float_16_tensor = float_32_tensor.type(dtype=torch.float16)

In [150]:

res = float_16_tensor * float_32_tensor
res.dtype
# This operation is correct

torch.float32

In [151]:
### Getting informations from a tensor
# Type: user .dtype
# Shape: .shape
# Device: .device

some_t = torch.rand(3, 5)
some_t

print(some_t)
print(f"ndim: {some_t.ndim}")
print(f"dtype: {some_t.dtype}")
print(f"shape: {some_t.shape}")
print(f"device: {some_t.device}")

tensor([[0.8073, 0.8787, 0.3620, 0.7175, 0.4652],
        [0.2695, 0.7101, 0.3664, 0.5961, 0.1099],
        [0.0417, 0.9678, 0.8049, 0.2852, 0.9984]])
ndim: 2
dtype: torch.float32
shape: torch.Size([3, 5])
device: cpu


In [152]:
### Manipulating tensors (tensor operations)

# This includes addition, sub, mult
# Devision
# Matrix multiplication

# Addition
t1 = torch.tensor([1, 2, 3])
t1 + 10

tensor([11, 12, 13])

In [153]:
# Mult
t1 * 10

tensor([10, 20, 30])

In [154]:
# Div
t1 / 10

tensor([0.1000, 0.2000, 0.3000])

In [155]:
# Built in torch operations
torch.mul(t1, 10)

tensor([10, 20, 30])

In [156]:
# Matrix mult
t1 = torch.randn(3)
t2 = torch.randn(3)
t1 ; t2

res_matmul = torch.matmul(t1, t2)
res_matmul.shape

t1 = torch.randn(3)
t2 = torch.randn( 3,1)
print(t2)
res_matmul = torch.matmul(t1, t2)
res_matmul.shape
print(res_matmul)

# Try with transpose
t1 = torch.randn(3)
t2 = torch.randn(3)
print(t2)
res_matmul = torch.matmul(t1, t2)
res_matmul.shape
print(res_matmul)


tensor([[1.1343],
        [1.2558],
        [2.1851]])
tensor([1.4042])
tensor([-0.5539, -1.5026, -0.0214])
tensor(0.6273)


In [157]:
t1 = torch.arange(1, 3)
t2 = torch.arange(1, 3)
res = torch.matmul(t1, t2)

res

tensor(5)

In [158]:
## line mult
def line_mul(t1, t2):
    val = torch.tensor(0)
    if len(t1) != len(t2): print("Tensor dim error"); return torch.tensor(0)
    for i in range(len(t1)):
        val += t1[i] * t2[i]
    res = val.clone().detach()
    return res




In [159]:
t3 = torch.arange(1, 9)
t4 = torch.arange(2, 10)

In [160]:
%%time
line_mul(t3, t4)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(240)

In [161]:
%%time
torch.matmul(t3, t4)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(240)

In [162]:
# Using built in function i better!! what a sulprise ...

In [163]:
# Matrix multiplication is very important
# We need to satisfy some rules 
# For this is Shapes rules

# We need to satisy
# - Inner dimension must match
#   - for example
#   - (3, 2) @ (3, 2) : NOT work !
#   - (2, 3) @ (3, 2) : Works!
#   - (3, 2) @ (2, 3) : Works!

t32 = torch.zeros(3, 2)
t23 = torch.zeros(2, 3)
try:
    t32 @ t32
except:
    print("Inner dimension not working")

#
print(t32 @ t23)
print(t23 @ t32)

# Other examples
t342 = torch.zeros(3, 4, 2)
t24 = torch.zeros(2, 4)
print((t342 @ t24).shape)


t342 = torch.zeros(3, 4, 2)
t324 = torch.zeros(3, 2, 4)
print(f": {(t342 @ t324).shape}")


Inner dimension not working
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0.],
        [0., 0.]])
torch.Size([3, 4, 4])
: torch.Size([3, 4, 4])


In [164]:
# The resulting matrix has the shape of the **outher dimensions**
t34 = torch.zeros(3, 4)
t42 = torch.zeros(4, 2)
(t34 @ t42).shape

torch.Size([3, 2])

In [165]:
# Shape erros
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6],
                         ])
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12],
                         ])

try: 
    torch.mm(tensor_A, tensor_B)
except: 
    print("RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)")

# I need to adjust the shape
# To fix shape we use transpose
# Transpose fixes the axes
tensor_B.T.shape

# If we transpose the shape changes
torch.mm(tensor_A, tensor_B.T)




RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [166]:
# Aggregations (min, max, avg, .... sum)
x = torch.arange(0, 100, 10)

In [167]:
torch.min(x), x.max()


(tensor(0), tensor(90))

In [168]:
# torch.mean(x) here datatype error
y = torch.arange(0, 100, 10, dtype=torch.float32)

In [169]:
y.mean()

tensor(45.)

In [170]:
dir(x)

['H',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__red

In [171]:
res = torch.max(x, dim=0, keepdim=False)
print(f"max is at: {res.indices}")

# this means that the position 9 of the tensor holds the max value
print(f"max has value: {x[res.indices.item()]}")

x.argmin()
x.argmax() # find max position


max is at: 9
max has value: 90


tensor(9)

In [172]:
# Reshaping, Stacking, squezeeing and unsqueezing tensors

# Reshape: reshapes a tensor
# View: return a view of an input tensor but in memory is the same
# Stacking: staks ternsos in new dimensions
# Squeeze: removes all 1 dimensions
# Unsqueezw: adds a 1 dimensions to a target tensor
# Permute: returns a view

x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [173]:
# add exstra dimension
x_reshaped = x.reshape(1, 9)

In [174]:
# In the reshape the number of elements must be the same

In [175]:
x.reshape(3, 3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [176]:
z = x.view(1, 9)

In [177]:
z

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [178]:
# A view of a tensor shares memory with a tensor that is a view of

In [179]:
# Stack
s = torch.stack([x, x, x, x])

In [180]:
s

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [181]:
## This uses the raw s to stack
torch.stack([s, s])

tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [182]:
# This staks hte column and combines them
torch.hstack([s, s])

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [183]:
# This staks rows and combines them
torch.vstack([s, s])

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [184]:
torch.stack([torch.arange(20, 30), torch.arange(100, 110)])

tensor([[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [185]:
torch.vstack([torch.arange(20, 30), torch.arange(100, 110)])

tensor([[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [186]:
torch.hstack([torch.arange(20, 30), torch.arange(100, 110)])

tensor([ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109])

In [187]:
torch.stack([torch.arange(20, 30), torch.arange(100, 110), torch.arange(100, 110)], dim=0)

tensor([[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [188]:
torch.stack([torch.arange(20, 30), torch.arange(100, 110), torch.arange(100, 110)], dim=1)

tensor([[ 20, 100, 100],
        [ 21, 101, 101],
        [ 22, 102, 102],
        [ 23, 103, 103],
        [ 24, 104, 104],
        [ 25, 105, 105],
        [ 26, 106, 106],
        [ 27, 107, 107],
        [ 28, 108, 108],
        [ 29, 109, 109]])

In [189]:

torch.stack([torch.arange(20, 30), torch.arange(100, 110), torch.arange(100, 110)], dim=-1)

tensor([[ 20, 100, 100],
        [ 21, 101, 101],
        [ 22, 102, 102],
        [ 23, 103, 103],
        [ 24, 104, 104],
        [ 25, 105, 105],
        [ 26, 106, 106],
        [ 27, 107, 107],
        [ 28, 108, 108],
        [ 29, 109, 109]])

In [190]:

torch.stack([torch.arange(20, 30), torch.arange(100, 110), torch.arange(100, 110)], dim=-2)

tensor([[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [191]:

torch.stack([torch.arange(20, 30), torch.arange(100, 110), torch.arange(100, 110)], dim=-0)

tensor([[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [192]:
torch.arange(200)

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 1

In [193]:
# Squeeze eliminates ndim 1 dimension from a tensor
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())

y = torch.squeeze(x)
print(y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])


In [196]:

y = torch.unsqueeze(x, dim=1)
print(y)

tensor([[[[[[0., 0.]],

           [[0., 0.]]]]],




        [[[[[0., 0.]],

           [[0., 0.]]]]]])


In [200]:
x = torch.arange(3, 8)
print(x)

tensor([3, 4, 5, 6, 7])


In [209]:
y = torch.unsqueeze(x, dim=-1)
print(y)

tensor([[3],
        [4],
        [5],
        [6],
        [7]])


In [215]:
# Permute - rearrange the shape
x_original = torch.randn(2,2,3) # h, w, colors
print(x_original)
# Permute
x_perm = x_original.permute(2, 0, 1) 
print(x_perm)



tensor([[[ 7.6530e-01, -9.4306e-01, -8.5150e-01],
         [ 1.7016e+00, -1.2386e+00, -2.7492e-01]],

        [[ 4.8794e-01,  1.2919e+00, -2.0994e-03],
         [-3.0646e-01, -1.9576e-02,  2.1656e+00]]])
tensor([[[ 7.6530e-01,  1.7016e+00],
         [ 4.8794e-01, -3.0646e-01]],

        [[-9.4306e-01, -1.2386e+00],
         [ 1.2919e+00, -1.9576e-02]],

        [[-8.5150e-01, -2.7492e-01],
         [-2.0994e-03,  2.1656e+00]]])


In [216]:
# Indexing 
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [218]:
# Index
x[0] # wil return the first bracket

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [219]:
x[0][0]

tensor([1, 2, 3])

In [220]:
x[0][0][0]

tensor(1)

In [222]:
# Get all values of 0 and 1 th dimentiosn and a range of the last
x[:, :, 1:3]

tensor([[[2, 3],
         [5, 6],
         [8, 9]]])

In [224]:
y = torch.rand(100, 100, 100, 100)

In [226]:
y[1:9, 2:5, 3:9, 1:2]

tensor([[[[9.0338e-01],
          [4.3346e-01],
          [5.7231e-01],
          [8.9646e-01],
          [9.6025e-01],
          [3.0231e-01]],

         [[4.8843e-01],
          [1.0189e-01],
          [5.3649e-01],
          [3.2506e-01],
          [8.9264e-01],
          [2.1197e-01]],

         [[2.3871e-01],
          [9.5569e-01],
          [5.1796e-01],
          [6.1196e-01],
          [2.3080e-02],
          [6.6039e-01]]],


        [[[6.7877e-01],
          [6.4058e-01],
          [5.8912e-01],
          [5.4093e-01],
          [5.9291e-01],
          [7.0892e-01]],

         [[7.4459e-01],
          [6.9112e-03],
          [8.0297e-01],
          [3.6107e-01],
          [6.2699e-01],
          [7.7505e-01]],

         [[9.0457e-01],
          [6.6116e-01],
          [5.2765e-02],
          [6.0778e-01],
          [4.6574e-01],
          [6.3687e-01]]],


        [[[1.8869e-01],
          [2.3135e-01],
          [5.2870e-01],
          [8.1627e-01],
          [3.0721e-02],


In [231]:
# Tensors and NumPy
# Sometimes you start with numpy and then use torch

# torch.from_numpy(ndarray)
import torch
import numpy as np
array = np.arange(1, 8)
tensor = torch.from_numpy(array)
print(tensor)
# Numpy uses float64 as default
tensor32 = torch.from_numpy(array).type(dtype=torch.float32)



tensor([1, 2, 3, 4, 5, 6, 7])


In [232]:
array = array + 1

In [234]:
array, tensor # numpy and torch dont share mem

t = torch.ones(9)
numpy_array = tensor.numpy()
numpy_array.dtype

dtype('int64')